--CREATE TABLE STOCK_VALUE_IPS_ITEM_060220
--AS Select * FROM STOCK_VALUE_IPS_ITEM;
--SELECT * FROM STOCK_VALUE_IPS_ITEM WHERE 1=1 AND SVBM_ID = 10;
--DELETE FROM STOCK_VALUE_IPS_ITEM WHERE 1=1 AND SVBM_ID = 2;
--COMMIT;

EXEC SP_STOCK_VALUE_IPS_NET ('202003',1);



SELECT ITM.ITEM_ID, ITM.ITEM_SHORT_DESC ITEM_NAME
, RATE_PREV RATE_NOV_19
, OPEN_QTY, OPEN_VALUE
, OPEN_QTY_DAMAGE
, OPEN_VALUE_DAMAGE
, PURCHASE_QTY
, PURCHASE_VALUE
, RATE_PURCHASE PURCHASE_RATE
, RATE_AVG
, SOLD_QTY, SOLD_VALUE
, SALES_RETURN_QTY, SALES_RETURN_VALUE
, REPLACE_QTY, REPLACE_VALUE
, CLOSE_QTY, CLOSE_VALUE
, CLOSE_QTY_DAMAGE
, CLOSE_VALUE_DAMAGE
FROM STOCK_VALUE_IPS_ITEM BI
INNER JOIN STOCK_VALUE_IPS_MST BM ON BI.SVBM_ID = BM.SVBM_ID
INNER JOIN SALES_ITEM_MST ITM ON BI.ITEM_CODE = ITM.ITEM_CODE
WHERE 1=1
AND BM.SVBM_MONTH_NO = '202003'
ORDER BY ITM.ITEM_SHORT_DESC
;

